# Generated by Django 4.0.7 on 2022-08-23 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-points']},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('author', 'points')},
        ),
    ]
