# Generated by Django 4.0.7 on 2022-08-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
