# Generated by Django 4.0.7 on 2022-08-25 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_alter_score_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
