# Generated by Django 4.0.7 on 2022-08-25 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_alter_score_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 25, 16, 8, 5, 736723, tzinfo=utc)),
        ),
    ]
