# Generated by Django 4.0.7 on 2022-08-25 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_alter_score_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 25, 16, 9, 1, 491897, tzinfo=utc)),
        ),
    ]
