# Generated by Django 4.0.7 on 2022-08-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_score_edited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='created_at',
        ),
    ]
